In [18]:
import numpy as np

In [19]:
na=np.array(range(1,6))
print(na)

[1 2 3 4 5]


In [20]:
type(na)

numpy.ndarray

In [21]:
TDA=np.array([[1,2,3],[4,5,6]])
print(Two_D_Array)

[[1 2 3]
 [4 5 6]]


In [22]:
flt=np.array([0.0,0.1,0.20,0.300,0.4])
flt

array([0. , 0.1, 0.2, 0.3, 0.4])

In [23]:
na.dtype

dtype('int64')

In [24]:
flt.dtype

dtype('float64')

In [25]:
print(np.ndim(TDA))

2


In [26]:
print(np.shape(TDA))

(2, 3)


In [27]:
flt.size

5

In [28]:
flt.itemsize

8

In [29]:
for r in TDA:
    for c in r:
        print(c,end=" ")
    print()

1 2 3 
4 5 6 


In [30]:
for i in TDA.flat:
    print(i,end=" ")

1 2 3 4 5 6 

In [34]:
import numpy as np
z=np.zeros(4)
y=np.ones(5)
x=np.ones((2,3),dtype=int)
print(z)
print(y)
print(x)

[0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]


In [38]:
num=np.arange(0,20)
print(num)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [43]:
num1=np.linspace(10,20,5)
print(num1)

[10.  12.5 15.  17.5 20. ]


In [40]:
num2=num.reshape(5,4)
print(num2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [45]:
mat=np.arange(1,100001).reshape(100,1000)
print(mat)

[[     1      2      3 ...    998    999   1000]
 [  1001   1002   1003 ...   1998   1999   2000]
 [  2001   2002   2003 ...   2998   2999   3000]
 ...
 [ 97001  97002  97003 ...  97998  97999  98000]
 [ 98001  98002  98003 ...  98998  98999  99000]
 [ 99001  99002  99003 ...  99998  99999 100000]]


In [49]:
n1=np.arange(1,6)
print(n1*3)
print(n1+n1)

[ 3  6  9 12 15]
[ 2  4  6  8 10]


In [50]:
nt=np.linspace(1.1,5.5,5)
print(nt)

[1.1 2.2 3.3 4.4 5.5]


In [51]:
print(n1*nt)

[ 1.1  4.4  9.9 17.6 27.5]


In [52]:
n1<nt

array([ True,  True,  True,  True,  True])

In [53]:
n1==nt

array([False, False, False, False, False])