In [5]:
import numpy as np
x=list(range(1000000))
y=np.array(x)
print(sum(x))
print(np.sum(y))
%timeit sum(x)
%timeit np.sum(y)

499999500000
499999500000
11.1 ms ± 897 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
751 μs ± 37.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [6]:
data=np.array([1,"hello"])
print(data)

['1' 'hello']


In [7]:
data=np.array([1,-0.5,7.9])
print(data)

[ 1.  -0.5  7.9]


In [8]:
da=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(da)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(np.shape(da))
print(np.ndim(da))

(3, 3)
2


In [10]:
print(da[0])

[1 2 3]


In [11]:
print(da[1,1])

5


In [12]:
print(np.shape(data))

(3,)


In [13]:
print(np.ndim(data))

1


In [14]:
print(da.shape)

(3, 3)


In [15]:
print(da.ndim)

2


In [16]:
arr=np.array([[1,2,3]])
print(arr.shape)
print(arr.ndim)

(1, 3)
2


In [17]:
arre=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arre.shape)
print(arre.ndim)
print(arre.size)
#2X2X3=12(All entries of shape, when multiplied gives you the size)

(2, 2, 3)
3
12


In [18]:
x=np.zeros(3)
print(x)

[0. 0. 0.]


In [19]:
y=np.zeros([2,3])
print(y)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
z=np.zeros([2,2,3])
print(z)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [21]:
xy=np.empty(2)
print(xy)

[8.55270055e-312 0.00000000e+000]


In [22]:
xz=np.empty([2,3,4])
print(xz)

[[[6.23042070e-307 1.89146896e-307 1.37961302e-306 6.89805830e-307]
  [1.33511562e-306 8.01097889e-307 1.78020169e-306 7.56601165e-307]
  [1.02359984e-306 1.33510679e-306 2.22522597e-306 8.01097889e-307]]

 [[1.42417629e-306 8.45593934e-307 6.89805151e-307 1.06811354e-306]
  [6.89807188e-307 9.34609111e-307 1.42419530e-306 1.42418172e-306]
  [1.37961641e-306 9.45699679e-308 2.22522596e-306 2.10077583e-312]]]


In [23]:
yz=np.zeros([3,6])
print(yz)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [24]:
yz=np.empty([3,6])
print(yz)#if there's an array that contains some elements in an array of the same size, the empty function provides that array without giving out array containing random values

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [25]:
zd=np.ones([1,2,3])
print(zd)

[[[1. 1. 1.]
  [1. 1. 1.]]]


In [26]:
md=np.arange(5)
print(md)

[0 1 2 3 4]


In [27]:
md=np.arange(1,5)
print(md)

[1 2 3 4]


In [28]:
md=np.arange(1,10,2)
print(md)

[1 3 5 7 9]


In [29]:
ms=np.arange(1,10,2,dtype=float)
print(ms)

[1. 3. 5. 7. 9.]


In [30]:
print(np.linspace(10,20,11)) 
#we can directly print np function without defining the array
#length of sub interval=(stop val-start val)/((no of elements to be generated)-1)
#provides the array inclusive of the last element

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]


In [31]:
print(np.full((2,3),'a'))#provides the constant array of the defined shape

[['a' 'a' 'a']
 ['a' 'a' 'a']]


In [32]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
print(np.eye(3))#similar to identity()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
print(np.eye(3, k=2))

[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [35]:
print(np.eye(3, k=-2))

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]


In [36]:
print(np.eye(3, k=4))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [37]:
print(np.array([1,2,3],dtype=np.float64))

[1. 2. 3.]


In [38]:
ar1=np.array([4,5,6])
ar2=ar1.astype(np.float64)
print(ar1,"now converted to",ar2)
print("Type of 2nd array: ",ar2.dtype)

[4 5 6] now converted to [4. 5. 6.]
Type of 2nd array:  float64


In [39]:
ar1=np.array([4.5,6])
ar2=ar1.astype(np.int32)
print(ar1,"now converted to",ar2)
print("Type of 2nd array: ",ar2.dtype)

[4.5 6. ] now converted to [4 6]
Type of 2nd array:  int32


In [40]:
ag1=np.array([[1,2,3]])
print(ag1)
print(ag1.shape)

[[1 2 3]]
(1, 3)


In [41]:
ag2=ag1.reshape(3,1)
print(ag2)
print(ag2.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [42]:
ag3=np.array([[1,2,3],[4,5,6]])
print(ag1)
print(ag1.shape)

[[1 2 3]]
(1, 3)


In [43]:
ag4=ag3.reshape(3,2)
print(ag4)
print(ag4.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [44]:
ag5=ag3.reshape(3)
print(ag5)

ValueError: cannot reshape array of size 6 into shape (3,)

In [ ]:
ag6=ag3.reshape(6,1)
print(ag6)

In [ ]:
ag6=ag3.reshape(6,1,1)
print(ag6)

In [ ]:
ag7=ag3.reshape(2,3,1,1)
print(ag7)

In [ ]:
ag8=ag3.ravel()
print(ag8)

In [ ]:
ato1=np.array([[1,2,3],[4,5,6]])
ato2=np.array([[7,8,9],[10,11,12]])
print(ato1+ato1)
print(ato1-ato1)
print(ato1*ato2)#this multiplication doesnt follow the general matrix multiplication rule
print(ato1*7)
print(ato1**2)
print(2**ato1)
print(7/ato1)

In [ ]:
ato1>ato2

In [ ]:
ato1<ato2

In [ ]:
ato1==ato1

In [ ]:
#we can also calculate number of trues or falses