# LAB ASSIGNMENT-1

Question 1:Take marks as input (0–100). Use if-elif-else to print the grade:
90–100 → A
75–89 → B
50–74 → C
Below 50 → Fail

In [24]:
import numpy as np

In [1]:
#Answer
TM=int(input("Enter your total marks: "))
if(TM>=90 and TM<=100):
    print("Grade: A")
elif(TM>=75 and TM<=89):
    print("Grade: B")
elif(TM>=50 and TM<=74):
    print("Grade: C")
else:
    print("Fail"):

Enter your total marks: 50
Grade: C


Question 2: Accept a number from the user and use a while loop to find the sum of its digits.

In [4]:
#Answer
n=int(input("Enter a number: "))
a=n
s=0
while(a>0):
    d=a%10
    s=s+d
    a=a//10
print("The sum of digits of the number ",n," is ",s)

Enter a number: 123
The sum of digits of the number  123  is  6


Question 3: Write a function is_prime(n) that returns True if a number is prime, otherwise False.
Test it for multiple values.

In [11]:
#Answer
def is_prime(n):
    a=1
    c=0
    while(a<=n):
        if(n%a==0):
            c=c+1
        a=a+1    
    if(c==2):
        return True
    return False
p=int(input("Enter a number "))
bo=is_prime(p)
if(bo==True):
    print("Prime")
else:
    print("Not prime")

Enter a number 12
Not prime


Question 4: Define a function is_palindrome(word) that checks whether a string is a palindrome or
not. Example: "madam" → Palindrome.

In [23]:
#Answer
def is_palindrome(word):
    s=""
    for a in word[::-1]:
        s=s+a
    print(s)
    if(word==s):
        print("Palindrome Word")
    else:
        print("Not a Palindrome Word")
m=input("Enter a word ")
is_palindrome(m)

Enter a word madam
madam
Palindrome Word


Question 5: Create two 3×3 matrices and perform:
a) Matrix multiplication
b) Determinant of a matrix
c) Inverse of a matrix (if possible)
Verify that multiplying a matrix with its inverse gives an identity matrix.

In [44]:
#Answer
ar1=[[ 7,  1,  4],
 [ 9,  5,  3],
 [ 2,  8,  6]]
ar2=[[ 2,  8,  1],
 [ 5,  4,  9],
 [ 3,  6,  7]]
ar3=np.dot(ar1,ar2)
dt1=np.linalg.det(ar1)
dt2=np.linalg.det(ar2)
print("Matrix Multiplication of ",ar1," and ",ar2," is: \n",ar3)
print("Determinant of ",ar1," is: ",dt1)
print("Determinant of ",ar2," is: ",dt2)
if(dt1==0):
    print("Inverse not possible for matrix",ar1)
else:
    iv1=np.linalg.inv(ar1)
    print("Inverse of the matrix ",ar1," is: \n",iv1)
if(dt2==0):
    print("Inverse not possible for matrix",ar2)
else:
    iv2=np.linalg.inv(ar2)
    print("Inverse of the matrix ",ar2," is: \n",iv2)

Matrix Multiplication of  [[7, 1, 4], [9, 5, 3], [2, 8, 6]]  and  [[2, 8, 1], [5, 4, 9], [3, 6, 7]]  is: 
 [[ 31  84  44]
 [ 52 110  75]
 [ 62  84 116]]
Determinant of  [[7, 1, 4], [9, 5, 3], [2, 8, 6]]  is:  242.00000000000009
Determinant of  [[2, 8, 1], [5, 4, 9], [3, 6, 7]]  is:  -97.99999999999996
Inverse of the matrix  [[7, 1, 4], [9, 5, 3], [2, 8, 6]]  is: 
 [[ 0.02479339  0.10743802 -0.07024793]
 [-0.19834711  0.14049587  0.06198347]
 [ 0.25619835 -0.2231405   0.10743802]]
Inverse of the matrix  [[2, 8, 1], [5, 4, 9], [3, 6, 7]]  is: 
 [[ 0.26530612  0.51020408 -0.69387755]
 [ 0.08163265 -0.1122449   0.13265306]
 [-0.18367347 -0.12244898  0.32653061]]


Question 6: Generate two NumPy arrays of 10 random integers each. Perform element-wise 
comparison (>, <, ==). Count how many times values in the first array are greater than 
the second.  

In [45]:
#Answer
import random
arr1=[]
arr2=[]
count=0
for a in range(0,10):
    arr1.append(random.randint(0,9))
    arr2.append(random.randint(0,9))
npa1=np.array(arr1)
npa2=np.array(arr2)
print("First Array: ",npa1)
print("Second Array: ",npa2)
'''for i in range(0,10):
    if(arr1[i]>arr2[i]):
        count=count+1'''
Grt_Elem=npa1>npa2
count=np.sum(Grt_Elem)
print("No. of times, first array has elements greater then second array: ",count)

First Array:  [4 0 4 2 6 3 9 4 1 8]
Second Array:  [7 7 8 1 0 6 8 7 1 6]
No. of times, first array has elements greater then second array:  4


Question 7: Suppose you have exam marks of 10 students stored in a Python list. Convert it into a
NumPy array and compute:
a) Average marks of the class
b) Students who scored above average

In [3]:
#Answer
import numpy as np
arr1=[89,78,95,91,87,85,80,75,97,73]
npa1=np.array(arr1)
avg=np.mean(npa1)
print("Students who scored above average")
for i in arr1:
    if(i>avg):
        print(i)

89
95
91
87
97


Question 8: Create a 4×4 NumPy array with values from 1 to 16. Perform the following: 
a) Extract the second row 
b) Extract the third column 
c) Slice the sub-matrix of shape (2×2) from the bottom-right corner

In [7]:
#Answer
da=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print("4X4 NumPy Array: ",da)
print("Second Row: ",da[1])
print("Third Column: ",da[:, 2])


4X4 NumPy Array:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Second Row:  [5 6 7 8]
Third Column:  [ 3  7 11 15]


Question 9: Create a (3×4) array with consecutive numbers from 1 to 12. Demonstrate the 
difference between reshape() and ravel(). 

In [6]:
da=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
da1=da.reshape(4,3)
da2=da.ravel()
print(da1)
print(da2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


Question 10: Simulate rolling a six-sided dice 1,000 times using NumPy’s random.randint(). Count 
the frequency of each outcome and display it as a dictionary (face → count).

In [ ]:
import random as r
