In [1]:
import numpy as np
num=np.arange(1,6)
num

array([1, 2, 3, 4, 5])

In [2]:
num2=num.view()
num2

array([1, 2, 3, 4, 5])

In [6]:
num3=num.copy()
num3

array([1, 2, 3, 4, 5])

In [7]:
num[1]*=10
num

array([ 1, 20,  3,  4,  5])

In [10]:
numbers2 = num[0:3]
numbers2

array([ 1, 20,  3])

In [8]:
#Shallow caopy the array method view returna new array objedct with a view of the original arrqay
#objerct data
#Both reshape and resize chnage the array dimensitons, reshape returns a view(shallow copy) of the
#original array with new dimensions, doesnt modify the original aray
#Resize modifies the original array


In [11]:
import numpy as np
grades = np.array([[87, 96, 70], [100,87, 90]])
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [12]:
grades.reshape(1, 6)

array([[ 87,  96,  70, 100,  87,  90]])

In [14]:
grades.resize(1, 6)
grades

array([[ 87,  96,  70, 100,  87,  90]])

In [ ]:
#flatten fucntion is used to flattehn a mutli dim array uinto 1 dim
#deepcopies original array data
#ravel also converts multi dim to signle dim,
#shallow copies original array

In [25]:
grades = np.array([[87, 96, 70], [100,87, 90]])
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [26]:
flattened = grades.flatten()
flattened

array([ 87,  96,  70, 100,  87,  90])

In [27]:
flattened[0] = 100
flattened

array([100,  96,  70, 100,  87,  90])

In [28]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [22]:
grades = np.array([[87, 96, 70], [100,87, 90]])
raveled = grades.ravel()
raveled

array([ 87,  96,  70, 100,  87,  90])

In [23]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [24]:
raveled[0] = 100
raveled

array([100,  96,  70, 100,  87,  90])

In [ ]:
grades

In [ ]:
#stacking means combining arrasys by adding more columns and more rows(2 types- horizontal and vertical) 

In [33]:
grades2 = np.array([[94, 77, 90], [100,81, 82]])
np.hstack((grades,grades2))

array([[ 87,  96,  70,  94,  77,  90],
       [100,  87,  90, 100,  81,  82]])

In [34]:
np.vstack((grades,grades2))

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [36]:
grades2.T

array([[ 94, 100],
       [ 77,  81],
       [ 90,  82]])