## Python for Computer Science and Data Science 1 (CSE 3651)

## MINOR ASSIGNMENT-6: NUMPY AND PANDAS

In [1]:
#1. Create a 2-by-3 array with ones, a 3-by-3 array with zeros and a 2-by-5 array with sevens.
import numpy as np
x=np.ones((2,3),dtype=int)
y=np.zeros((2,3),dtype=int)
z=np.full((2,5),7)
print(x)
print(y)
print(z)

[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]
[[7 7 7 7 7]
 [7 7 7 7 7]]


In [7]:
#2. Use arange to create a 2-by-2 array containing the numbers 0-3. Use broadcasting to perform each
# of the following operations on the original array:
#(a) Cube every element of the array.
#(b) Add 7 to every element of the array.
#(c) Multiply every element of the array by 2.
import numpy as np
x=np.arange(0,4).reshape(2,2)
print("Original Array \n",x)
print("Cube \n",x**3)
print("Adding 7 to each element \n",x+7)
print("Multiplying 2 to each element \n",x*2)

Original Array 
 [[0 1]
 [2 3]]
Cube 
 [[ 0  1]
 [ 8 27]]
Adding 7 to each element 
 [[ 7  8]
 [ 9 10]]
Multiplying 2 to each element 
 [[0 2]
 [4 6]]


In [15]:
#3. Create a 3-by-3 array containing the even integers from 2 through 18. Create a second 3-by-3
# array containing the integers from 9 down to 1, then multiply the first array by the second.
import numpy as np
x=np.arange(2,19,2).reshape(3,3)
print("arr1 \n",x)
y=np.arange(9,0,-1).reshape(3,3)
print("arr2 \n",y)
z=x*y
print("Resultant Array \n",z)

arr1 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
arr2 
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Resultant Array 
 [[18 32 42]
 [48 50 48]
 [42 32 18]]


In [27]:
#4. Create a 2D array and swap the first two rows and two columns.
import numpy as np
x=np.array([[1,2],[3,4]])
print("Original Array \n",x)
y=x[[1,0]]
print("Swapping first 2 rows \n",y)
z=x[:,[1,0]]
print("Swapping first 2 columns \n",z)

Original Array 
 [[1 2]
 [3 4]]
Swapping first 2 rows 
 [[3 4]
 [1 2]]
Swapping first 2 columns 
 [[2 1]
 [4 3]]


In [37]:
#4. Create a 2D array and swap the first two rows and two columns.
import numpy as np
x=np.array([[1,2],[3,4]])
x1=x.copy()
x2=x.copy()
print("Original Array \n",x)
x1[[0,1]]=x1[[1,0]]
print("Swapping first 2 rows \n",x1)
x1[:,[0,1]]=x1[:,[1,0]]
print("Swapping first 2 columns \n",x1)

Original Array 
 [[1 2]
 [3 4]]
Swapping first 2 rows 
 [[3 4]
 [1 2]]
Swapping first 2 columns 
 [[2 1]
 [4 3]]


In [42]:
#5. Create a 2-by-5 array from an argument which is a list of the two five-element
#lists [2, 3, 5, 7, 11] and [13, 17, 19, 23, 29].
import numpy as np
l1=[[2,3,5,7,11],[13,17,19,24,29]]
x=np.array(l1).reshape(2,5)
print(x)

[[ 2  3  5  7 11]
 [13 17 19 24 29]]


In [43]:
#6. Create a 2-by-3 array containing the first six powers of 2 beginning with 2^0.
#Flatten the array first with method flatten, then with ravel. In each case,
#display the result then display the original array to show that it was unmodified.
import numpy as np
a=np.array([2**i for i in range(0,6)]).reshape(2,3)
print("Original array: \n",a)
a1=a.flatten()
print("Flattened array: \n",a1)
a2=a.ravel()
print("Ravelled array: \n",a2)

Original array: 
 [[ 1  2  4]
 [ 8 16 32]]
Flattened array: 
 [ 1  2  4  8 16 32]
Ravelled array: 
 [ 1  2  4  8 16 32]


In [48]:
#7.Find the most frequent values in an array of positive integers. The original 
#array is [6 9 5 1 7 5 1 0 1 5 5 0 8 9 0 7 0 7 6 5 1 1 9 5 3 8 7 9 6 3 4 5 9 7 2 
#7 0 2 2 6].
import numpy as np
import statistics as st
x=np.array([6,9,5,1,7,5,1,0,1,5,5,0,8,9,0,7,0,7,6,5,1,1,9,5,3,8,7,9,6,3,4,5,9,7,2,7,0,2,2,6])
y=st.mode(x)
print("Most frequent value in the array is: ",y)

Most frequent value in the array is:  5


In [52]:
#8. (needs to change) Use linspace and reshape to create a 2-by-3 array with the 
#values 1.1. 2.2. . . . ,6.6. Then use astype to convert the array to an array
#of integers.
import numpy as np
x=np.linspace(1.1,6.6,6).reshape(2,3).astype(int)
print(x)

[[1 2 3]
 [4 5 6]]


23.1