In [1]:
#Printing squares of 1 to 3

In [2]:
for i in[1,2,3,4]:
    print(i*i)

1
4
9
16


In [19]:
for i in [1,2,3,4]:
    print(i*i,end=" ")

1 4 9 16 

In [5]:
for i in range(1,5):
    print(i)

1
2
3
4


In [8]:
for i in range(0,11,2):
    print(i)

0
2
4
6
8
10


In [10]:
i=0
while(i<4):
    print(i)
    i=i+1

0
1
2
3


In [11]:
i=10
while(i>0):
    print(i)
    i=i-1

10
9
8
7
6
5
4
3
2
1


In [15]:
i=int(input("Enter a number: "))
p=1
for a in range(1,i+1):
    p=p*a
print("Factorial: ", p)    

Enter a number5
Factorial:  120


In [16]:
import numpy as np

In [17]:
x=np.array([1,2,3])
print(x)

[1 2 3]


In [20]:
a=[1,2,3]
x=np.array(a)
print(x)

[1 2 3]


In [26]:
x=list(range(1000000))
z=np.array(x)
%timeit sum(x)
%timeit np.sum(z)

7.36 ms ± 11.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
322 µs ± 3.99 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [28]:
da=np.array([1.5,-3.35])
print(da,"type= ",type(da))

[ 1.5  -3.35] type=  <class 'numpy.ndarray'>


In [30]:
mat=np.array([[1,2,3,4],[5,6,7,8]])
print(mat)

[[1 2 3 4]
 [5 6 7 8]]
